/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fm_middlewareimpl_interf_KeyManagerAbs */

#ifndef _Included_com_fm_middlewareimpl_interf_KeyManagerAbs
#define _Included_com_fm_middlewareimpl_interf_KeyManagerAbs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fm_middlewareimpl_interf_KeyManagerAbs
 * Method:    setImgPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fm_middlewareimpl_interf_KeyManagerAbs_setImgPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fm_middlewareimpl_interf_KeyManagerAbs
 * Method:    aml_key_write
 * Signature: (Ljava/lang/String;[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fm_middlewareimpl_interf_KeyManagerAbs_aml_1key_1write
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     com_fm_middlewareimpl_interf_KeyManagerAbs
 * Method:    aml_key_read
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fm_middlewareimpl_interf_KeyManagerAbs_aml_1key_1read
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fm_middlewareimpl_interf_KeyManagerAbs
 * Method:    aml_key_get_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fm_middlewareimpl_interf_KeyManagerAbs_aml_1key_1get_1name
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
